import Link from "next/link";
import { ArrowLeft, Bookmark, ExternalLink, ShieldCheck } from "lucide-react";
import { notFound } from "next/navigation";
import { PulseScore } from "@/components/pulse-score";
import { Sidebar } from "@/components/sidebar";
import { mockOffers } from "@/data/mock-offers";

export default async function OfferPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const offer = mockOffers.find((item) => item.id === id); if (!offer) notFound();
  const max = Math.max(...offer.history.map((item) => item.activeAds));
  return <div className="app-shell"><Sidebar/><main className="detail"><header className="detail-top"><Link href="/"><ArrowLeft size={17}/> Voltar ao radar</Link><span className="mock-label">DADOS DE DEMONSTRAÇÃO · MOCK</span></header><section className="offer-hero"><img src={offer.thumbnail} alt=""/><div><p className="eyebrow">OFERTA MONITORADA · MOCK</p><h1>{offer.name}</h1><p>por {offer.advertiser} · {offer.country} · {offer.language}</p><div className="tags"><span>{offer.niche}</span><span>{offer.subniche}</span><span>{offer.productFormat}</span></div><div className="detail-actions"><a href={offer.landingPageUrl} target="_blank"><ExternalLink size={15}/> Landing page MOCK</a><button><ShieldCheck size={15}/> Validar TikTok</button><button><Bookmark size={15}/> Salvar</button></div></div><PulseScore score={offer.pulseScore}/></section><section className="detail-grid"><article className="insight-card"><h2>Leitura da oferta</h2><dl><div><dt>HEADLINE</dt><dd>{offer.headline}</dd></div><div><dt>PROMESSA</dt><dd>{offer.promise}</dd></div><div><dt>FORMATO</dt><dd>{offer.productFormat}</dd></div><div><dt>PREÇO OBSERVADO</dt><dd>R$ {offer.observedPrice.toFixed(2).replace(".", ",")}</dd></div></dl></article><article className="insight-card"><h2>Métricas observadas</h2><div className="large-metrics"><div><b>{offer.activeAds}</b><span>Anúncios ativos</span></div><div><b>{offer.creativeCount}</b><span>Criativos</span></div><div><b>{offer.oldestAdDays}</b><span>Dias ativo do anúncio</span></div><div><b>{offer.history.length}</b><span>Dias observados pelo Sinal Pulse</span></div></div></article></section><section className="history-card"><div><p className="eyebrow">HISTÓRICO PULSE · MOCK</p><h2>Evolução de anúncios ativos</h2><p>Dados demonstrativos. Quantidade de anúncios não representa vendas ou faturamento.</p></div><div className="chart">{offer.history.map((point) => <div className="bar-point" key={point.date}><span style={{height: `${(point.activeAds / max) * 100}%`}}/><b>{point.activeAds}</b><small>{point.date}</small></div>)}</div></section></main></div>;
}
